export const GET_ORDER_NUMBER_SUCCESS = "GET_ORDER_NUMBER_SUCCESS";
export const GET_ORDER_NUMBER_FAILED = "GET_ORDER_NUMBER_FAILED";
export const GET_ORDER_REQUEST = "GET_ORDER_REQUEST";

export const GET_INGREDIENTS_REQUEST = "GET_INGREDIENTS_REQUEST";
export const GET_INGREDIENTS_FAILED = "GET_INGREDIENTS_FAILED";
export const GET_INGREDIENTS_SUCCESS = "GET_INGREDIENTS_SUCCESS";

export const REMOVE_CURRENT_INGREDIENT = -"REMOVE_CURRENT_INGREDIENT";
export const ADD_CURRENT_INGREDIENT = "ADD_CURRENT_INGREDIENT";
export const CLEAR_SELECTED_INGREDIENT_LIST = "CLEAR_SELECTED_INGREDIENT_LIST";
export const RESET_TOTAL_PRICE = "RESET_TOTAL_PRICE";
export const SET_TOTAL_PRICE = "SET_TOTAL_PRICE";
export const DELETE_SELECTED_INGREDIENT = "DELETE_SELECTED_INGREDIENT";
export const ADD_SELECTED_INGREDIENT = "ADD_SELECTED_INGREDIENT";

export const RESET_ORDER_NUMBER = "RESET_ORDER_NUMBER";
export const GET_ORDER_NUMBER_REQUEST = "GET_ORDER_NUMBER_REQUEST";
export const CLEAR_INGREDIENT_LIST_COUNT = "CLEAR_INGREDIENT_LIST_COUNT";
export const DECREASE_COUNT = "DECREASE_COUNT";
export const INCREASE_COUNT = "INCREASE_COUNT";

export const OPEN_INGREDIENT_MODAL = "OPEN_INGREDIENT_MODAL";
export const CLOSE_ALL_MODAL = "CLOSE_ALL_MODAL";
export const OPEN_ORDER_MODAL = "OPEN_ORDER_MODAL";
