export const GET_ORDER_NUMBER_SUCCESS: "GET_ORDER_NUMBER_SUCCESS" =
  "GET_ORDER_NUMBER_SUCCESS";
export const GET_ORDER_NUMBER_FAILED: "GET_ORDER_NUMBER_FAILED" =
  "GET_ORDER_NUMBER_FAILED";
export const GET_ORDER_REQUEST: "GET_ORDER_REQUEST" = "GET_ORDER_REQUEST";

export const GET_INGREDIENTS_REQUEST: "GET_INGREDIENTS_REQUEST" =
  "GET_INGREDIENTS_REQUEST";
export const GET_INGREDIENTS_FAILED: "GET_INGREDIENTS_FAILED" =
  "GET_INGREDIENTS_FAILED";
export const GET_INGREDIENTS_SUCCESS: "GET_INGREDIENTS_SUCCESS" =
  "GET_INGREDIENTS_SUCCESS";

export const REMOVE_CURRENT_INGREDIENT: "REMOVE_CURRENT_INGREDIENT" =
  "REMOVE_CURRENT_INGREDIENT";
export const ADD_CURRENT_INGREDIENT: "ADD_CURRENT_INGREDIENT" =
  "ADD_CURRENT_INGREDIENT";
export const CLEAR_SELECTED_INGREDIENT_LIST: "CLEAR_SELECTED_INGREDIENT_LIST" =
  "CLEAR_SELECTED_INGREDIENT_LIST";
export const DELETE_SELECTED_INGREDIENT: "DELETE_SELECTED_INGREDIENT" =
  "DELETE_SELECTED_INGREDIENT";
export const ADD_SELECTED_INGREDIENT: "ADD_SELECTED_INGREDIENT" =
  "ADD_SELECTED_INGREDIENT";

export const RESET_ORDER_NUMBER: "RESET_ORDER_NUMBER" = "RESET_ORDER_NUMBER";
export const GET_ORDER_NUMBER_REQUEST: "GET_ORDER_NUMBER_REQUEST" =
  "GET_ORDER_NUMBER_REQUEST";
export const CLEAR_INGREDIENT_LIST_COUNT: "CLEAR_INGREDIENT_LIST_COUNT" =
  "CLEAR_INGREDIENT_LIST_COUNT";
export const DECREASE_COUNT: "DECREASE_COUNT" = "DECREASE_COUNT";
export const INCREASE_COUNT: "INCREASE_COUNT" = "INCREASE_COUNT";

export const RESET_INGREDIENTS: "RESET_INGREDIENTS" = "RESET_INGREDIENTS";
export const OPEN_ORDER_MODAL: "OPEN_ORDER_MODAL" = "OPEN_ORDER_MODAL";

export const UPDATE_TYPE: "UPDATE_TYPE" = "UPDATE_TYPE";
export const CHANGE_SELECTED_INGREDIENT: "CHANGE_SELECTED_INGREDIENT" = "CHANGE_SELECTED_INGREDIENT";
export const MOVE_INGREDIENT: "MOVE_INGREDIENT" = "MOVE_INGREDIENT";

export const RESET_PASSWORD_FAILED: "RESET_PASSWORD_FAILED"= "RESET_PASSWORD_FAILED";
export const RESET_PASSWORD_REQUEST: "RESET_PASSWORD_REQUEST" = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS: "RESET_PASSWORD_SUCCESS" = "RESET_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAILED: "CHANGE_PASSWORD_FAILED" = "CHANGE_PASSWORD_FAILED";
export const CHANGE_PASSWORD_REQUEST: "CHANGE_PASSWORD_REQUEST" = "CHANGE_PASSWORD_REQUEST";
export const CHANGE_PASSWORD_SUCCESS: "CHANGE_PASSWORD_SUCCESS" = "CHANGE_PASSWORD_SUCCESS";

export const GET_REGISTRATION_REQUEST: "GET_REGISTRATION_REQUEST" = "GET_REGISTRATION_REQUEST";
export const GET_REGISTRATION_FAILED: "GET_REGISTRATION_FAILED" = "GET_REGISTRATION_FAILED";
export const GET_REGISTRATION_SUCCESS: "GET_REGISTRATION_SUCCESS" = "GET_REGISTRATION_SUCCESS";
export const GET_LOGIN_REQUEST: "GET_LOGIN_REQUEST" = "GET_LOGIN_REQUEST";
export const GET_LOGIN_FAILED: "GET_LOGIN_FAILED" = "GET_LOGIN_FAILED";
export const GET_LOGIN_SUCCESS: "GET_LOGIN_SUCCESS" = "GET_LOGIN_SUCCESS";
export const GET_LOGOUT_REQUEST: "GET_LOGOUT_REQUEST" = "GET_LOGOUT_REQUEST";
export const GET_LOGOUT_SUCCESS: "GET_LOGOUT_SUCCESS" = "GET_LOGOUT_SUCCESS";
export const GET_LOGOUT_FAILED: "GET_LOGOUT_FAILED" = "GET_LOGOUT_FAILED";
export const GET_TOKEN_UPDATE_REQUEST: "GET_TOKEN_UPDATE_REQUEST" = "GET_TOKEN_UPDATE_REQUEST";
export const GET_TOKEN_UPDATE_SUCCESS: "GET_TOKEN_UPDATE_SUCCESS" = "GET_TOKEN_UPDATE_SUCCESS";
export const GET_TOKEN_UPDATE_FAILED: "GET_TOKEN_UPDATE_FAILED" = "GET_TOKEN_UPDATE_FAILED";
export const GET_USER_INFO_REQUEST: "GET_USER_INFO_REQUEST" = "GET_USER_INFO_REQUEST";
export const GET_USER_INFO_FAILED: "GET_USER_INFO_FAILED" = "GET_USER_INFO_FAILED";
export const GET_USER_INFO_SUCCESS: "GET_USER_INFO_SUCCESS" = "GET_USER_INFO_SUCCESS";
export const UPDATE_USER_INFO_REQUEST: "UPDATE_USER_INFO_REQUEST" = "UPDATE_USER_INFO_REQUEST";
export const UPDATE_USER_INFO_FAILED: "UPDATE_USER_INFO_FAILED" = "UPDATE_USER_INFO_FAILED";
export const UPDATE_USER_INFO_SUCCESS: "UPDATE_USER_INFO_SUCCESS" = "UPDATE_USER_INFO_SUCCESS";
