export const GET_ORDERS_REQUEST: 'GET_ORDERS_REQUEST' = 'GET_ORDERS_REQUEST'
export const GET_ORDERS_SUCCESS: 'GET_ORDERS_SUCCESS' = 'GET_ORDERS_SUCCESS'
export const GET_ORDERS_FAILED: 'GET_ORDERS_FAILED' = 'GET_ORDERS_FAILED'

export const MODAL_INFO_ORDER_OPEN: 'MODAL_INFO_ORDER_OPEN' = 'MODAL_INFO_ORDER_OPEN'
export const MODAL_INFO_ORDER_CLOSE: 'MODAL_INFO_ORDER_CLOSE' = 'MODAL_INFO_ORDER_CLOSE'
export const LINK_OPEN_INFO_ORDER: 'LINK_OPEN_INFO_ORDER' = 'LINK_OPEN_INFO_ORDER'